[build]
  publish = ".next"
  command = "npm run build"
  ignore = "if [ \"$CONTEXT\" = \"production\" ]; then exit 0; fi"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"