import type { Metadata } from "next";
import { Figtree, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ToasterProvider } from "./components/ToasterProvider";
import SessionWrapper from "./components/SessionWrapper";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // CSS variable name
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", figtree.variable, inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ToasterProvider />
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  );
}
